package com.myorganisation.CareEmoPilot.model.enums;

public enum AreaType {
    // Inbuilt
    RELATIONSHIP,
    OCD,
    ANXIETY,

    // Core Mental Health Specializations
    DEPRESSION,
    ANXIETY_DISORDERS,
    STRESS_MANAGEMENT,
    BURNOUT,
    BIPOLAR_DISORDER,
    OBSESSIVE_COMPULSIVE_DISORDER,
    PANIC_ATTACKS,
    POST_TRAUMATIC_STRESS_DISORDER,
    ATTENTION_DEFICIT_HYPERACTIVITY_DISORDER,
    BORDERLINE_PERSONALITY_DISORDER,
    EATING_DISORDERS,
    SUBSTANCE_ABUSE_ADDICTION,
    SLEEP_DISORDERS_INSOMNIA,
    SCHIZOPHRENIA_PSYCHOSIS,
    ANGER_ISSUES_RAGE_CONTROL,
    GRIEF_LOSS,
    SELF_HARM_SUICIDAL_THOUGHTS,
    MOOD_DISORDERS,
    SOCIAL_ANXIETY,
    PHOBIAS,

    // Life & Emotional Challenges
    LOW_SELF_ESTEEM_SELF_CONFIDENCE,
    RELATIONSHIP_ISSUES,
    BREAKUPS_DIVORCE_RECOVERY,
    MARITAL_COUPLE_COUNSELING,
    FAMILY_CONFLICTS,
    PARENTING_SUPPORT,
    ACADEMIC_PRESSURE_EXAM_ANXIETY,
    WORKPLACE_STRESS,
    CAREER_CONFUSION_JOB_BURNOUT,
    LIFE_TRANSITIONS,
    LONELINESS_ISOLATION,
    PERSONAL_GROWTH_SELF_DISCOVERY,
    EMOTIONAL_REGULATION_OVERTHINKING,
    INNER_CHILD_HEALING,
    PERFECTIONISM,
    BODY_IMAGE_ISSUES
}
